apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: app
        image: mpcrockdocker/devops-app:cbfc067a51ba0e9a73cff3aed936e09e42616ae9
        ports:
        - containerPort: 5000
